<?php
/* 
    SCF: Tipos de contenidos
*/

add_action( 'init', function() {
	register_post_type( 'especialidad', array(
	'labels' => array(
		'name' => 'Especialidades',
		'singular_name' => 'Especialidad',
		'menu_name' => 'Especialidades',
		'all_items' => 'Todas las Especialidades',
		'edit_item' => 'Editar Especialidad',
		'view_item' => 'Ver Especialidad',
		'view_items' => 'Ver Especialidades',
		'add_new_item' => 'Agregar Especialidad',
		'add_new' => 'Agregar Especialidad',
		'new_item' => 'Nueva Especialidad',
		'parent_item_colon' => 'Especialidad superior:',
		'search_items' => 'Buscar Especialidades',
		'not_found' => 'No se han encontrado especialidades',
		'not_found_in_trash' => 'No hay especialidades en la papelera',
		'archives' => 'Archivo de Especialidad',
		'attributes' => 'Atributos de Especialidad',
		'insert_into_item' => 'Insertar en especialidad',
		'uploaded_to_this_item' => 'Subido a este especialidad',
		'filter_items_list' => 'Filtrar lista de especialidades',
		'filter_by_date' => 'Filtrar especialidades por fecha',
		'items_list_navigation' => 'Navegación por la lista de Especialidades',
		'items_list' => 'Lista de Especialidades',
		'item_published' => 'Especialidad publicado.',
		'item_published_privately' => 'Especialidad publicado de forma privada.',
		'item_reverted_to_draft' => 'Especialidad devuelto a borrador.',
		'item_scheduled' => 'Especialidad programados.',
		'item_updated' => 'Especialidad actualizado.',
		'item_link' => 'Enlace a Especialidad',
		'item_link_description' => 'Un enlace a un especialidad.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-awards',
	'supports' => array(
		0 => 'title',
	),
	'taxonomies' => array(
		0 => 'tipo-especialidad',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'experto', array(
	'labels' => array(
		'name' => 'Expertos',
		'singular_name' => 'Experto',
		'menu_name' => 'Expertos',
		'all_items' => 'Todos los Expertos',
		'edit_item' => 'Editar Experto',
		'view_item' => 'Ver Experto',
		'view_items' => 'Ver Expertos',
		'add_new_item' => 'Agregar Experto',
		'add_new' => 'Agregar Experto',
		'new_item' => 'Nuevo Experto',
		'parent_item_colon' => 'Experto superior:',
		'search_items' => 'Buscar Expertos',
		'not_found' => 'No se han encontrado expertos',
		'not_found_in_trash' => 'No hay expertos en la papelera',
		'archives' => 'Archivo de Experto',
		'attributes' => 'Atributos de Experto',
		'insert_into_item' => 'Insertar en experto',
		'uploaded_to_this_item' => 'Subido a este experto',
		'filter_items_list' => 'Filtrar lista de expertos',
		'filter_by_date' => 'Filtrar expertos por fecha',
		'items_list_navigation' => 'Navegación por la lista de Expertos',
		'items_list' => 'Lista de Expertos',
		'item_published' => 'Experto publicado.',
		'item_published_privately' => 'Experto publicado de forma privada.',
		'item_reverted_to_draft' => 'Experto devuelto a borrador.',
		'item_scheduled' => 'Experto programados.',
		'item_updated' => 'Experto actualizado.',
		'item_link' => 'Enlace a Experto',
		'item_link_description' => 'Un enlace a un experto.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-groups',
	'supports' => array(
		0 => 'title',
		1 => 'custom-fields',
		2 => 'Categoría ',
	),
	'taxonomies' => array(
		0 => 'area',
	),
	'has_archive' => 'equipo',
	'rewrite' => false,
	'delete_with_user' => false,
) );

	register_post_type( 'fecu', array(
	'labels' => array(
		'name' => 'FECU Social',
		'singular_name' => 'FECU Social',
		'menu_name' => 'FECU Social',
		'all_items' => 'Todas las FECU Social',
		'edit_item' => 'Editar FECU Social',
		'view_item' => 'Ver FECU Social',
		'view_items' => 'Ver FECU Social',
		'add_new_item' => 'Agregar FECU Social',
		'add_new' => 'Agregar FECU Social',
		'new_item' => 'Nuevo FECU Social',
		'parent_item_colon' => 'FECU Social superior:',
		'search_items' => 'Buscar FECU Social',
		'not_found' => 'No se han encontrado fecu social',
		'not_found_in_trash' => 'No hay fecu social en la papelera',
		'archives' => 'Archivo de FECU Social',
		'attributes' => 'Atributos de FECU Social',
		'insert_into_item' => 'Insertar en fecu social',
		'uploaded_to_this_item' => 'Subido a este fecu social',
		'filter_items_list' => 'Filtrar lista de fecu social',
		'filter_by_date' => 'Filtrar fecu social por fecha',
		'items_list_navigation' => 'Navegación por la lista de FECU Social',
		'items_list' => 'Lista de FECU Social',
		'item_published' => 'FECU Social publicado.',
		'item_published_privately' => 'FECU Social publicado de forma privada.',
		'item_reverted_to_draft' => 'FECU Social devuelto a borrador.',
		'item_scheduled' => 'FECU Social programados.',
		'item_updated' => 'FECU Social actualizado.',
		'item_link' => 'Enlace a FECU Social',
		'item_link_description' => 'Un enlace a un fecu social.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-code-standards',
	'supports' => array(
		0 => 'title',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'galeria-de-videos', array(
	'labels' => array(
		'name' => 'Galería de videos',
		'singular_name' => 'Video',
		'menu_name' => 'Galería de Videos',
		'all_items' => 'Todos los Videos',
		'edit_item' => 'Editar Video',
		'view_item' => 'Ver Video',
		'view_items' => 'Ver Videos',
		'add_new_item' => 'Agregar Video',
		'add_new' => 'Agregar Video',
		'new_item' => 'Nuevo Video',
		'parent_item_colon' => 'Video superior:',
		'search_items' => 'Buscar Videos',
		'not_found' => 'No se han encontrado videos',
		'not_found_in_trash' => 'No hay videos en la papelera',
		'archives' => 'Archivo de Video',
		'attributes' => 'Atributos de Video',
		'insert_into_item' => 'Insertar en video',
		'uploaded_to_this_item' => 'Subido a este video',
		'filter_items_list' => 'Filtrar lista de videos',
		'filter_by_date' => 'Filtrar videos por fecha',
		'items_list_navigation' => 'Navegación por la lista de Videos',
		'items_list' => 'Lista de Videos',
		'item_published' => 'Video publicado.',
		'item_published_privately' => 'Video publicado de forma privada.',
		'item_reverted_to_draft' => 'Video devuelto a borrador.',
		'item_scheduled' => 'Video programados.',
		'item_updated' => 'Video actualizado.',
		'item_link' => 'Enlace a Video',
		'item_link_description' => 'Un enlace a un video.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-format-video',
	'supports' => array(
		0 => 'title',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'galeria-de-fotos', array(
	'labels' => array(
		'name' => 'Galerías de fotos',
		'singular_name' => 'Galería de fotos',
		'menu_name' => 'Galerías de fotos',
		'all_items' => 'Todas las Galerías de Fotos',
		'edit_item' => 'Editar Galería de fotos',
		'view_item' => 'Ver Galería de fotos',
		'view_items' => 'Ver Galerías de Fotos',
		'add_new_item' => 'Agregar Galería de fotos',
		'add_new' => 'Agregar Galería de fotos',
		'new_item' => 'Nueva Galería de fotos',
		'parent_item_colon' => 'Galería de fotos superior:',
		'search_items' => 'Buscar Galerías de Fotos',
		'not_found' => 'No se han encontrado galerías de fotos',
		'not_found_in_trash' => 'No hay galerías de fotos en la papelera',
		'archives' => 'Archivo de Galería de fotos',
		'attributes' => 'Atributos de Galería de fotos',
		'insert_into_item' => 'Insertar en galería de fotos',
		'uploaded_to_this_item' => 'Subido a esta galería de fotos',
		'filter_items_list' => 'Filtrar lista de galerías de fotos',
		'filter_by_date' => 'Filtrar galerías de fotos por fecha',
		'items_list_navigation' => 'Navegación por la lista de Galerías de Fotos',
		'items_list' => 'Lista de Galerías de Fotos',
		'item_published' => 'Galería de fotos publicada.',
		'item_published_privately' => 'Galería de fotos publicado de forma privada.',
		'item_reverted_to_draft' => 'Galería de fotos devuelto a borrador.',
		'item_scheduled' => 'Galería de fotos programadas.',
		'item_updated' => 'Galería de fotos actualizada.',
		'item_link' => 'Enlace a Galería de fotos',
		'item_link_description' => 'Un enlace a un galería de fotos.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-format-gallery',
	'supports' => array(
		0 => 'title',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'newsletter', array(
	'labels' => array(
		'name' => 'Newsletters',
		'singular_name' => 'Newsletter',
		'menu_name' => 'Newsletters',
		'all_items' => 'Todos los Newsletters',
		'edit_item' => 'Editar Newsletter',
		'view_item' => 'Ver Newsletter',
		'view_items' => 'Ver Newsletters',
		'add_new_item' => 'Agregar Newsletter',
		'add_new' => 'Agregar Newsletter',
		'new_item' => 'Nuevo Newsletter',
		'parent_item_colon' => 'Newsletter superior:',
		'search_items' => 'Buscar Newsletters',
		'not_found' => 'No se han encontrado newsletters',
		'not_found_in_trash' => 'No hay newsletters en la papelera',
		'archives' => 'Archivo de Newsletter',
		'attributes' => 'Atributos de Newsletter',
		'insert_into_item' => 'Insertar en newsletter',
		'uploaded_to_this_item' => 'Subido a este newsletter',
		'filter_items_list' => 'Filtrar lista de newsletters',
		'filter_by_date' => 'Filtrar newsletters por fecha',
		'items_list_navigation' => 'Navegación por la lista de Newsletters',
		'items_list' => 'Lista de Newsletters',
		'item_published' => 'Newsletter publicado.',
		'item_published_privately' => 'Newsletter publicado de forma privada.',
		'item_reverted_to_draft' => 'Newsletter devuelto a borrador.',
		'item_scheduled' => 'Newsletter programados.',
		'item_updated' => 'Newsletter actualizado.',
		'item_link' => 'Enlace a Newsletter',
		'item_link_description' => 'Un enlace a un newsletter.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-email-alt',
	'supports' => array(
		0 => 'title',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'noticia', array(
	'labels' => array(
		'name' => 'Noticias',
		'singular_name' => 'Noticia',
		'menu_name' => 'Noticias',
		'all_items' => 'Todas las Noticias',
		'edit_item' => 'Editar Noticia',
		'view_item' => 'Ver Noticia',
		'view_items' => 'Ver Noticias',
		'add_new_item' => 'Agregar Noticia',
		'add_new' => 'Agregar Noticia',
		'new_item' => 'Nueva Noticia',
		'parent_item_colon' => 'Noticia superior:',
		'search_items' => 'Buscar Noticias',
		'not_found' => 'No se han encontrado noticias',
		'not_found_in_trash' => 'No hay noticias en la papelera',
		'archives' => 'Archivo de Noticia',
		'attributes' => 'Atributos de Noticia',
		'insert_into_item' => 'Insertar en noticia',
		'uploaded_to_this_item' => 'Subido a esta noticia',
		'filter_items_list' => 'Filtrar lista de noticias',
		'filter_by_date' => 'Filtrar noticias por fecha',
		'items_list_navigation' => 'Navegación por la lista de Noticias',
		'items_list' => 'Lista de Noticias',
		'item_published' => 'Noticia publicada.',
		'item_published_privately' => 'Noticia publicada de forma privada.',
		'item_reverted_to_draft' => 'Noticia devuelta a borrador.',
		'item_scheduled' => 'Noticia programada.',
		'item_updated' => 'Noticia actualizada.',
		'item_link' => 'Enlace a Noticia',
		'item_link_description' => 'Un enlace a un noticia.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-format-aside',
	'supports' => array(
		0 => 'title',
		1 => 'excerpt',
	),
	'taxonomies' => array(
		0 => 'categoria',
		1 => 'etiqueta',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'publicacion', array(
	'labels' => array(
		'name' => 'Publicaciones',
		'singular_name' => 'Publicación',
		'menu_name' => 'Publicaciones',
		'all_items' => 'Todas las Publicaciones',
		'edit_item' => 'Editar Publicación',
		'view_item' => 'Ver Publicación',
		'view_items' => 'Ver Publicaciones',
		'add_new_item' => 'Agregar Publicación',
		'add_new' => 'Agregar Publicación',
		'new_item' => 'Nuevo Publicación',
		'parent_item_colon' => 'Publicación superior:',
		'search_items' => 'Buscar Publicaciones',
		'not_found' => 'No se han encontrado publicaciones',
		'not_found_in_trash' => 'No hay publicaciones en la papelera',
		'archives' => 'Archivo de Publicación',
		'attributes' => 'Atributos de Publicación',
		'insert_into_item' => 'Insertar en publicación',
		'uploaded_to_this_item' => 'Subido a este publicación',
		'filter_items_list' => 'Filtrar lista de publicaciones',
		'filter_by_date' => 'Filtrar publicaciones por fecha',
		'items_list_navigation' => 'Navegación por la lista de Publicaciones',
		'items_list' => 'Lista de Publicaciones',
		'item_published' => 'Publicación publicado.',
		'item_published_privately' => 'Publicación publicado de forma privada.',
		'item_reverted_to_draft' => 'Publicación devuelto a borrador.',
		'item_scheduled' => 'Publicación programados.',
		'item_updated' => 'Publicación actualizado.',
		'item_link' => 'Enlace a Publicación',
		'item_link_description' => 'Un enlace a un publicación.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-welcome-learn-more',
	'supports' => array(
		0 => 'title',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'testimonio', array(
	'labels' => array(
		'name' => 'Testimonios',
		'singular_name' => 'Testimonio',
		'menu_name' => 'Testimonios',
		'all_items' => 'Todos los Testimonios',
		'edit_item' => 'Editar Testimonio',
		'view_item' => 'Ver Testimonio',
		'view_items' => 'Ver Testimonios',
		'add_new_item' => 'Agregar Testimonio',
		'add_new' => 'Agregar Testimonio',
		'new_item' => 'Nuevo Testimonio',
		'parent_item_colon' => 'Testimonio superior:',
		'search_items' => 'Buscar Testimonios',
		'not_found' => 'No se han encontrado testimonios',
		'not_found_in_trash' => 'No hay testimonios en la papelera',
		'archives' => 'Archivo de Testimonio',
		'attributes' => 'Atributos de Testimonio',
		'insert_into_item' => 'Insertar en testimonio',
		'uploaded_to_this_item' => 'Subido a este testimonio',
		'filter_items_list' => 'Filtrar lista de testimonios',
		'filter_by_date' => 'Filtrar testimonios por fecha',
		'items_list_navigation' => 'Navegación por la lista de Testimonios',
		'items_list' => 'Lista de Testimonios',
		'item_published' => 'Testimonio publicado.',
		'item_published_privately' => 'Testimonio publicado de forma privada.',
		'item_reverted_to_draft' => 'Testimonio devuelto a borrador.',
		'item_scheduled' => 'Testimonio programados.',
		'item_updated' => 'Testimonio actualizado.',
		'item_link' => 'Enlace a Testimonio',
		'item_link_description' => 'Un enlace a un testimonio.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-format-chat',
	'supports' => array(
		0 => 'title',
	),
	'delete_with_user' => false,
) );
} );


add_filter( 'enter_title_here', function( $default, $post ) {
	switch ( $post->post_type ) {
		case 'especialidad':
			return 'Nombre de la Especialidad';
		case 'experto':
			return 'Nombre del experto';
		case 'testimonio':
			return 'Agregar Nombre';
	}

	return $default;
}, 10, 2 );

